# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: Build+Test CI

on: [pull_request, push]

jobs:
  glibc:
    strategy:
      matrix:
        cc: [gcc, clang]
        abi: [-m64, -m32]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      CC: ${{ matrix.cc }} ${{ matrix.abi }}
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install build-essential gcc gcc-multilib clang automake autoconf autoconf-archive libtool pax-utils -qy

    - uses: actions/checkout@v3
      name: Checkout

    - name: Build
      run: |
        ./autogen.sh
        ./configure || { cat config.log; false; }
        make V=1
        make V=1 check || { cat tests/testsuite.log; false; }
        make V=1 distcheck

  musl:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: --cap-add=SYS_PTRACE
    steps:
      - name: Install dependencies
        run: apk add bash coreutils build-base automake autoconf autoconf-archive libtool pax-utils gawk sed

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          ./autogen.sh
          ./configure || { cat config.log; false; }
          make V=1
          make V=1 check || { cat tests/testsuite.log; false; }
